# Generated by Django 3.2.11 on 2022-01-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allergy_potential', models.IntegerField(default=1, blank=False)),
                ('date_pub', models.DateTimeField(blank = False)),
            ],
        ),
    ]
