# Generated by Django 3.2 on 2021-12-06 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alergycalc', '0002_alter_meal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(max_length=200)),
                ('ingredient1', models.CharField(max_length=200)),
                ('ingredient2', models.CharField(max_length=200)),
                ('ingredient3', models.CharField(max_length=200)),
                ('ingredient4', models.CharField(max_length=200)),
                ('ingredient5', models.CharField(max_length=200)),
                ('eating_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('symptoms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
